repos:
- repo: local
  hooks:
    - id: pip-audit
      name: pip-audit
      entry: pip-audit -r requirements.txt
      language: system
      pass_filenames: false
      always_run: true

    - id: bandit
      name: bandit
      entry: python -m bandit -r src/ -ll
      language: system
      types: [python]
      pass_filenames: false